# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDD0010024():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_dD0010024(self):
    self.driver.get("https://school.moodledemo.net/login/index.php?loginredirect=1")
    self.driver.set_window_size(1024, 768)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("privacyofficer")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    self.driver.find_element(By.ID, "loginbtn").click()
    self.driver.find_element(By.LINK_TEXT, "Site administration").click()
    self.driver.find_element(By.LINK_TEXT, "Users").click()
    self.driver.find_element(By.LINK_TEXT, "Data deletion").click()
    self.driver.find_element(By.CSS_SELECTOR, ".float-right:nth-child(3) > .btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".modal-footer > .btn-secondary").click()
    # The expired context still presents
    elements = self.driver.find_elements(By.ID, "expired-contexts-table_r0_c0")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "user-menu-toggle").click()
    self.driver.find_element(By.LINK_TEXT, "Log out").click()
    self.driver.close()
  
